# Generated by Django 6.0.5 on 2026-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="expensedb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRAVEL", "Travel"),
                            ("BILLS", "Bills"),
                            ("GYM", "Gym"),
                            ("ENTERTAINMENT", "Entertainment"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
